In [12]:
from pymongo import MongoClient
# from auth import username, password
import urllib
from pprint import pprint
from tqdm.notebook import tqdm
import multiprocessing
from transformers import AutoTokenizer, TFAutoModel
import pickle
import os
import tensorflow as tf
import preprocessor as p

p.set_options(p.OPT.URL, p.OPT.EMOJI)

In [2]:
# setup pickle data dir
data_dir = 'data'

if not os.path.exists(data_dir):
    os.makedirs(data_dir)

In [3]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
# model = TFAutoModel.from_pretrained("bert-base-uncased")

# inputs = tokenizer("Hello world!", return_tensors="tf")
# outputs = model(**inputs)

In [4]:
username = 'christian'
password = 'Dec211996'

In [5]:
client = MongoClient('mongodb://' + urllib.parse.quote_plus(username) + ':' + urllib.parse.quote_plus(password) + '@198.211.115.252')

In [12]:
ignore_mask = ['test_db', 'admin', 'local', 'config', 'TwitterJobs']
conspiracies = list(set(client.list_database_names()) - set(ignore_mask))

In [7]:
# def worker(consp_tuple):
#     data = []
#     conspiracy, hashtag = consp_tuple
#     cursor = client[conspiracy][hashtag].find({})
#     for document in tqdm(cursor):
#         try:
#             inputs = tokenizer(p.clean(document['text']), return_tensors="tf")
#             inputs.update({'tweetId' : document['tweetId']})
#             data.append(inputs)
#         except Exception as e:
#             pass
        
#     print(len(data))
#     with open(data_dir + '/' + conspiracy + '-' + hashtag + '.p', 'wb') as f:
#         pickle.dump(data, f)
    

In [8]:
# consp_tuples = []
# for conspiracy in conspiracies:
#     for hashtag in client[conspiracy].list_collection_names():
#         consp_tuples.append((conspiracy, hashtag))

In [9]:
# pool = multiprocessing.Pool(multiprocessing.cpu_count())

In [6]:
with open('../src/data/alexjones-hashtag_newswars.p', 'rb') as handle:
    data = pickle.load(handle)

In [42]:
data[0]

{'input_ids': <tf.Tensor: shape=(1, 101), dtype=int32, numpy=
array([[  101,  2469,  1010,  1030, 13109,  2015,  3490, 18032,  1010,
         2017,  2071,  3191,  1030,  7110,  2239,  4179,  2012,  1001,
         1041,  3676,  3401, 14526,  1012,  2021,  2017,  2113,  1030,
         5734, 28075,  2265,  2739,  2097,  2031,  1996,  2190,  6325,
          999,  1025,  1007,  1001,  2739,  9028,  2015,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0]])>, 'token_type_ids': <tf.Tensor: shape=(1, 101), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 